[profile.default]
src = "src"
out = "out"
solc_version = "0.8.22"
optimizer = true
optimizer_runs = 200
fs_permissions = [{ access = "read", path = "./"}]

libs = [
    # We provide a set of useful contract utilities
    # in the lib directory of @layerzerolabs/toolbox-foundry:
    # 
    # - forge-std
    # - ds-test
    # - solidity-bytes-utils
    'node_modules/@layerzerolabs/toolbox-foundry/lib',
    'node_modules',
]

remappings = [
    "ds-test/=node_modules/@layerzerolabs/toolbox-foundry/lib/ds-test/",
    "forge-std/=node_modules/@layerzerolabs/toolbox-foundry/lib/forge-std/",
    
    "@layerzerolabs/=node_modules/@layerzerolabs/",
    "@openzeppelin/=node_modules/@openzeppelin/",
    "@solidstate/contracts/=lib/solidstate-solidity/contracts/",

    "@pythnetwork/pyth-sdk-solidity/=lib/pyth-sdk-solidity",
    "solidity-bytes-utils/=node_modules/solidity-bytes-utils/",
    "solmate/=lib/solmate/",
]

[profile.default.rpc_endpoints]
holesky = "${RPC_URL_HOLESKY}"
sepolia = "${RPC_URL_SEPOLIA}"
arbitrum-sepolia = "${RPC_URL_ARBITRUM_SEPOLIA}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
