[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200

remappings = [
  "@solidstate/contracts=lib/solidstate-solidity/contracts",
  "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
  "@openzeppelin/contracts-upgradeable=lib/openzeppelin-contracts-upgradeable/contracts",
  "@layerzerolabs/solidity-examples=lib/solidity-examples",
  "@pythnetwork/pyth-sdk-solidity/=lib/pyth-sdk-solidity",
  "@api3/contracts=lib/contracts/contracts",
  "solmate=lib/solmate/src",
  "@layerzerolabs/oapp-evm/=lib/devtools/packages/oapp-evm/",
  "@layerzerolabs/lz-evm-protocol-v2/=lib/layerzero-v2/packages/layerzero-v2/evm/protocol",
  "@layerzerolabs/oft-evm/=lib/devtools/packages/oft-evm/",
  "@layerzerolabs/oapp-upgradeable/contracts=lib/LayerZero-v2.git/oapp/contracts",
  "@layerzerolabs/lz-evm-messagelib-v2/contracts=lib/LayerZero-v2.git/oapp/contracts",
  "@layerzerolabs/test-devtools-evm-foundry/=lib/devtools/packages/test-devtools-evm-foundry/",

]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
