[profile.default]
src = "src"
out = "out"
# evm_version = "london" # used for BEVM mainnet
solc_version = "0.8.22"
optimizer = true
optimizer_runs = 200
fs_permissions = [{ access = "read", path = "./"}]

libs = ['lib']

remappings = [
    "solidity-bytes-utils/=node_modules/solidity-bytes-utils/",
    "@layerzerolabs/=node_modules/@layerzerolabs/",

    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
    "@openzeppelin/contracts-upgradeable=lib/openzeppelin-contracts-upgradeable/contracts",
    "@solidstate/contracts/=lib/solidstate-solidity/contracts/",
    "@pythnetwork/pyth-sdk-solidity/=lib/pyth-sdk-solidity",
    "solmate/=lib/solmate/",
    "@api3/contracts=lib/contracts/contracts",
]

[fmt] # See https://book.getfoundry.sh/reference/config/formatter
int_types             = "long"
line_length           = 120
bracket_spacing       = true
multiline_func_header = "all"
number_underscore     = "thousands"
quote_style           = "double"
sort_imports          = true
ignore                = ['./lib/**/*']

[profile.default.rpc_endpoints]
holesky = "${RPC_URL_HOLESKY}"
sepolia = "${RPC_URL_SEPOLIA}"
arbitrum-sepolia = "${RPC_URL_ARBITRUM_SEPOLIA}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
